version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Test
          command: gradle test
      - store_test_results:
          path: build/test-results

  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: MakeJar
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: build/libs
          paths:
            - .

workflows:
  version: 2
  three_job_flow:
    jobs:
      - test
      - package:
          requires:
            - test