version: 2.0
jobs:
  checkout:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test
          command: gradle test
      - store_test_results:
          path: build/test-results

  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: MakeJar
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix

workflows:
  version: 2
  three_job_flow:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - package:
          requires:
            - test